import os
import sys
import random
from sqlalchemy.orm import Session
from datetime import datetime, timedelta

# Ensure we can import app modules
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from backend.app.database import SessionLocal
from backend.app.models import Lead, Account, Contact, Opportunity, Asset, Product
from backend.app.utils.sf_id import get_id
from backend.app.utils.timezone import get_kst_now_naive

def seed_data():
    db = SessionLocal()
    
    first_names = ["James", "Mary", "John", "Patricia", "Robert", "Jennifer", "Michael", "Linda", "William", "Elizabeth", "David"]
    last_names = ["Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis", "Rodriguez", "Martinez"]
    domains = ["example.com", "test.org", "demo.net", "corp.com"]
    companies = ["Acme Corp", "Tech Solutions", "Global Industries", "Stark Enterprises", "Wayne Corp"]
    
    print("Seeding 10 Leads...")
    for i in range(10):
        fn = random.choice(first_names)
        ln = random.choice(last_names)
        lead = Lead(
            id=get_id("Lead"),
            first_name=fn,
            last_name=ln,
            email=f"{fn.lower()}.{ln.lower()}@{random.choice(domains)}",
            phone=f"555-{random.randint(100, 999)}-{random.randint(1000, 9999)}",
            status=random.choice(["New", "Open", "Working", "Qualified"]),
            gender=random.choice(["Male", "Female"]),
            description="Generated by Phase 21 seeding script",
            created_at=get_kst_now_naive(),
            updated_at=get_kst_now_naive()
        )
        db.add(lead)

    print("Seeding 10 Accounts...")
    accounts = []
    for i in range(10):
        acc = Account(
            id=get_id("Account"),
            name=f"{random.choice(companies)} {random.randint(100, 999)}",
            is_person_account=random.choice([True, False]),
            record_type=random.choice(["Corporate", "Individual"]),
            industry=random.choice(["Technology", "Finance", "Healthcare", "Automotive"]),
            website=f"www.{random.choice(companies).replace(' ', '').lower()}.com",
            status="Active",
            created_at=get_kst_now_naive(),
            updated_at=get_kst_now_naive()
        )
        db.add(acc)
        db.flush()
        accounts.append(acc)

    print("Seeding 10 Contacts...")
    for i in range(10):
        acc = random.choice(accounts)
        fn = random.choice(first_names)
        ln = random.choice(last_names)
        contact = Contact(
            id=get_id("Contact"),
            account_id=acc.id,
            first_name=fn,
            last_name=ln,
            email=f"{fn.lower()}.{ln.lower()}@{random.choice(domains)}",
            phone=f"555-{random.randint(100, 999)}-{random.randint(1000, 9999)}",
            gender=random.choice(["Male", "Female", "Other"]),
            created_at=get_kst_now_naive(),
            updated_at=get_kst_now_naive()
        )
        db.add(contact)

    print("Seeding 10 Opportunities...")
    for i in range(10):
        acc = random.choice(accounts)
        opp = Opportunity(
            id=get_id("Opportunity"),
            account_id=acc.id,
            name=f"Deal - {acc.name} - {random.randint(1000, 9999)}",
            amount=random.randint(10000, 500000),
            stage=random.choice(["Prospecting", "Qualification", "Needs Analysis", "Value Proposition", "Closed Won", "Closed Lost"]),
            status="Open",
            probability=random.randint(10, 90),
            close_date=(get_kst_now_naive() + timedelta(days=random.randint(10, 90))).date(),
            created_at=get_kst_now_naive(),
            updated_at=get_kst_now_naive()
        )
        db.add(opp)

    print("Seeding 10 Products...")
    products = []
    for i in range(10):
        prod = Product(
            id=get_id("Product"),
            name=f"Standard Vehicle Model {i+1}",
            description="Standard features, high liability limits.",
            base_price=random.randint(30000, 150000),
            created_at=get_kst_now_naive(),
            updated_at=get_kst_now_naive()
        )
        db.add(prod)
        db.flush()
        products.append(prod)

    print("Seeding 10 Assets...")
    for i in range(10):
        acc = random.choice(accounts)
        prod = random.choice(products)
        asset = Asset(
            id=get_id("Asset"),
            account_id=acc.id,
            product_id=prod.id,
            name=f"{prod.name} for {acc.name}",
            vin=f"1HGCM82633A{random.randint(100000, 999999)}",
            status=random.choice(["Purchased", "Registered", "Shipped"]),
            purchase_date=(get_kst_now_naive() - timedelta(days=random.randint(10, 300))).date(),
            created_at=get_kst_now_naive(),
            updated_at=get_kst_now_naive()
        )
        db.add(asset)

    db.commit()
    print("Seeding complete.")

if __name__ == "__main__":
    seed_data()
